databases:
  - name: farmdb
    plan: free
    databaseName: farmdb
    user: farmuser

services:
  - type: web
    plan: free
    name: farm-management
    runtime: python
    rootDir: farm_management               # This points to the second folder with manage.py
    buildCommand: ./build.sh
    startCommand: >
      python -m gunicorn farm_management.asgi:application
      -k uvicorn.workers.UvicornWorker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: farmdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: your-render-subdomain.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: |
          https://farmmanagement.netlify.app,
          http://localhost:5173
      - key: WEB_CONCURRENCY
        value: "4"
