# Generated by Django 5.2.1 on 2025-05-28 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.crop'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='status',
            field=models.CharField(choices=[('Planting', 'Planting'), ('Growing', 'Growing'), ('Harvesting', 'Harvesting')], default='Planting', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
