# Generated by Django 5.2.1 on 2025-05-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='unit',
            field=models.CharField(blank=True, choices=[('kgs', 'Kilograms'), ('litres', 'Litres'), ('units', 'Units'), ('tons', 'Tons'), ('gallons', 'Gallons')], default='units', max_length=20, null=True),
        ),
    ]
