# Generated by Django 5.2.1 on 2025-05-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_resource_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='usage_status',
            field=models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('depleted', 'Depleted')], default='available', max_length=20),
        ),
    ]
